'use client';
import{useEffect,useState}from'react';
type D={skills:any[];categories:any[];links:any[]};
export default function Admin(){const[ok,setOk]=useState(false),[pw,setPw]=useState(''),[d,setD]=useState<D>({skills:[],categories:[],links:[]}),[tab,setTab]=useState<'skills'|'categories'|'links'>('skills'),[f,setF]=useState<any>({});
async function load(){const r=await fetch('/api/admin/data');if(r.ok){setD(await r.json());setOk(true)}}useEffect(()=>{load()},[]);
async function login(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:pw})});if(r.ok){setPw('');load()}else alert('Invalid password')}
async function save(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/data',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:tab,...f})});if(!r.ok){alert((await r.json()).error);return}setF({});load()}
async function del(type:string,id:number){if(!confirm('Delete this item?'))return;await fetch('/api/admin/data',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({type,id})});load()}
if(!ok)return <main className="admin-shell"><div className="admin-login"><b>doably</b><h1>Admin</h1><p>Manage skills, categories and links.</p><form onSubmit={login}><input type="password" placeholder="Admin password" value={pw} onChange={e=>setPw(e.target.value)}/><button>Sign in</button></form></div></main>;
return <main className="admin-shell"><header className="admin-head"><a href="/">← Doably</a><button onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});location.reload()}}>Log out</button></header><div className="admin-tabs">{(['skills','categories','links']as const).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><section className="admin-card"><h2>Add {tab.slice(0,-1)}</h2><form className="admin-form" onSubmit={save}>
{tab==='skills'&&<><input required placeholder="Name" value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="slug" value={f.slug||''} onChange={e=>setF({...f,slug:e.target.value})}/></>}
{tab==='categories'&&<><input required placeholder="Name" value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="slug" value={f.slug||''} onChange={e=>setF({...f,slug:e.target.value})}/><textarea required placeholder="Description" value={f.description||''} onChange={e=>setF({...f,description:e.target.value})}/><select required value={f.skillId||''} onChange={e=>setF({...f,skillId:e.target.value})}><option value="">Attach to skill…</option>{d.skills.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></>}
{tab==='links'&&<><select required value={f.categoryId||''} onChange={e=>setF({...f,categoryId:e.target.value})}><option value="">Choose category…</option>{d.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input required placeholder="Article title" value={f.title||''} onChange={e=>setF({...f,title:e.target.value})}/><input required placeholder="https://..." value={f.url||''} onChange={e=>setF({...f,url:e.target.value})}/><input placeholder="Source" value={f.source||''} onChange={e=>setF({...f,source:e.target.value})}/><input type="number" placeholder="Priority" value={f.priority||0} onChange={e=>setF({...f,priority:e.target.value})}/></>}
<button className="save">Save</button></form></section><section className="admin-card"><h2>{tab}</h2>{d[tab].map((x:any)=><div className="admin-row" key={x.id}><div><b>{x.name||x.title}</b><small>{x.description||x.url||x.category_name}</small></div><button onClick={()=>del(tab.slice(0,-1),x.id)}>Delete</button></div>)}</section></main>}
